name: README Auto Refresh

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:        # allow manual runs

permissions:
  contents: write           # required so scheduled runs can push

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update README timestamp
        shell: bash
        run: |
          set -euo pipefail
          stamp="<!--last_refresh--> Last refreshed: $(date -u '+%Y-%m-%d %H:%M UTC')"

          if grep -q "<!--last_refresh-->" README.md; then
            sed -i "s|<!--last_refresh-->.*|$stamp|g" README.md
          else
            printf "\n---\n%s\n" "$stamp" >> README.md
          fi

      - name: Commit and push if changed
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-refresh README [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
